/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package animals;

import animals.model.AnimalFactory;

import java.io.PrintStream;

public class App {
    private final LandAnimalPrinter landAnimalPrinter;
    private final SeaAnimalPrinter seaAnimalPrinter;

    public App(AnimalFactory animalFactory, PrintStream printStream) {
        this.landAnimalPrinter = LandAnimalPrinter.instance(animalFactory, printStream);
        this.seaAnimalPrinter = SeaAnimalPrinter.instance(animalFactory, printStream);
    }

    public void run() {
        landAnimalPrinter.print();
        seaAnimalPrinter.print();
    }

    public static void main(String[] args) {
        new App(AnimalFactory.instance(), System.out).run();
    }
}
