/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package animals;

import animals.model.AnimalFactory;

public class App {
    private final LandAnimalPrinter landAnimalPrinter;
    private final SeaAnimalPrinter seaAnimalPrinter;

    public App(AnimalFactory animalFactory) {
        this.landAnimalPrinter = LandAnimalPrinter.instance(animalFactory);
        this.seaAnimalPrinter = SeaAnimalPrinter.instance(animalFactory, System.out);
    }

    public void run() {
        landAnimalPrinter.print();
        seaAnimalPrinter.print();
    }

    public static void main(String[] args) {
        new App(AnimalFactory.instance()).run();
    }
}
